version: '3'

services:
  db:
    build: ./mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql

  wordpress:
    links:
      - db
    build: ./woocommerce/
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - ./data/html:/var/www/html
      - ./data/log:/var/log
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 8080:80
